### ISSUE TITLE
build insulated algae box

### ISSUE THREAD

**Issue by srconstantin** [srconstantin/daphnia#2]
- construct box from foam

- use Dremel to cut holes & insert heat sinks & fans & power supply

- foam cure

- test for temperature control

**Comment by srconstantin** [comment]
Do we want a peltier-cooled vessel? Or just a container in a minifridge? TBD.

**Comment by jpxgotts** [comment]
Previous testing with Peltier coolers indicated that a normally sized heat sink and convective/radiative dissipation were insufficient to maintain a proper temperature gradient when driven by any voltage.

Yesterday's experiments with an oversize heat sink and fan circulation (from which hard temperature data was logged) will be continued today, and I expect to be able to achieve 34°F without much difficulty.

After that, maintaining that temperature will be a software issue 😊
