### ISSUE TITLE
install lights (daylight and IR) in cooler, and set lights on a 12:12 schedule

### ISSUE THREAD

**Issue by srconstantin** [srconstantin/daphnia#3]

**Comment by jpxgotts** [comment]
Daylight LEDs have been affixed to inside of container lid with ethylene vinyl acetate hot-melt adhesive. Space has been left to permit the addition of permanent silicone adhesive later, if this mounting location is viable and no modifications need to be made to the light bar itself.

Some issues have arisen with camera visibility with the light bars installed and the lid shut -- images seem to be badly overexposed, and this will have to be corrected.

The timer has been installed and given a test program to turn on and off over the course of several minutes; as of now, it's succeeded in switching them on and off at the prescribed time.
