### ISSUE TITLE
Install Daphnia & camera mount in Yeti cooler

### ISSUE THREAD

**Issue by srconstantin** [srconstantin/daphnia#8]
- Get additional acrylic boxes from container store

- build second steel frame for 2nd Daphnia box & 2nd camera

- attach both mounts to the Yeti cooler

**Comment by jpxgotts** [comment]
Extruded aluminum rails and associated hardware were ordered yesterday and should be arriving tomorrow.

A second acrylic tank is still needed.

After the tank is obtained, there will be a 24h delay before it can be used, for curing of the silicone sealant.

There is a potential issue with regards to the placement of fluid fittings on the sides of the tanks not fitting in the cooler; either another arrangement (vs. side-by-side) will have to be devised for the tanks, or new tanks with differently oriented fittings will have to be built.
