### ISSUE TITLE
Build pump & filter system

### ISSUE THREAD

**Issue by srconstantin** [srconstantin/daphnia#9]
- connect sterile filter loop to each Daphnia box with sterile silicone tubing

- connect algae vessel to Daphnia box with sterile silicone tubing

- run tubing through peristaltic pump

- test entire system with water

**Comment by jpxgotts** [comment]
Plumbing tests can be run when the ice cube gets built the rest of the way out (i.e. today, If this test type successfully gets it down to 34°, and later if it doesn't).

Sterile tubing should be separated from stock beforehand, as to avoid the waste of contaminating fresh tubing.

Framing won't arrive until tomorrow, so it can't be tested in its ultimate configuration as of yet, but we can run them on the bench fine, I think.
